# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TargetPlace',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.CharField(max_length=1024, verbose_name='descrption')),
                ('time', models.CharField(max_length=50, verbose_name='time')),
                ('region', models.CharField(max_length=50, verbose_name='region')),
                ('url', models.CharField(max_length=1024, verbose_name='url')),
                ('pointX', models.FloatField(verbose_name='point_x')),
                ('pointY', models.FloatField(verbose_name='point_y')),
            ],
        ),
    ]
