# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsing_data', '0002_auto_20170214_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_data', models.BinaryField()),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('tagetplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsing_data.TargetPlace')),
            ],
        ),
    ]
