# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsing_data', '0003_targetimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='targetimage',
            old_name='tagetplace',
            new_name='targetplace',
        ),
    ]
